### PR TITLE
adding openvswitch functional tests

### PR DESCRIPTION
**Pull request by radez**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/211

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
looks like we are having some fallout from centos 7.7, maybe stale mirror. Added depends-on to test fix, if so, we'll merge it

**Comment by privateip** [comment]
This is related to #30 so that I can have a local inventory file that I can pass to `tox -e func` for testing in my local infra.  The version of `tox` in the distro is old enough that it doesn't support passing the `env` values in

**Comment by pabelanger** [comment]
recheck

**Pull request merged**
