### PR TITLE
Add support for ExtremeNetworks Networking Operating System switches

### PR DESCRIPTION
**Pull request by naved001**
This was tested against a Brocade VDX 6740 running NOS 7.0.2

### CODE REVIEW

**Comment by naved001** [comment]
@radez @larsks @tzumainn This is ready for review

**Review by larsks — APPROVED** [review]
Looks good to me.

**Review by radez — APPROVED** [review]
lgtm, I've set the gate label. I think that's what will merge it.

**Comment by naved001** [comment]
thanks @radez! Looks like even with the label set this didn't merge

**Comment by radez** [comment]
I saw that, I've emailed someone to try and figure out why.

**Comment by tzumainn** [comment]
@radez hi! is there any update on this?

**Comment by radez** [comment]
Seems my contact for this is not at the company any more. Let me find a different person, or if you know anyone related?

**Pull request closed without merging**
